name: od_rai_mamba
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - lightgbm
  - imbalanced-learn
  - matplotlib
  - seaborn
  - ipywidgets
  - widgetsnbextension   # ensures widgets render in Notebook/Lab
  - jupyterlab
  - notebook
  - ipykernel
  - joblib
  - threadpoolctl
  - statsmodels
  # RAI stack from conda-forge
  - fairlearn
  - dice-ml
  - raiutils
  - responsibleai
  - interpret-community
  - erroranalysis
  - econml
  - pip
  - pip:
      - raiwidgets
