name: od_rai_lgbm
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - lightgbm
  - imbalanced-learn
  - matplotlib
  - seaborn
  - ipywidgets
  - jupyterlab
  - notebook
  - ipykernel
  - joblib
  - threadpoolctl
  - statsmodels
  - erroranalysis
  - interpret-community
  - fairlearn
  - econml
  - dice-ml
  - raiutils
  - responsibleai
  - raiwidgets
  - interpret-community
  - erroranalysis
