name: od_rai_lgbm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - lightgbm
  - imbalanced-learn
  - matplotlib
  - seaborn
  - ipywidgets
  - jupyterlab
  - notebook
  - ipykernel
  - joblib
  - threadpoolctl
  - statsmodels
  - pip:
      - responsibleai
      - raiwidgets
      - interpret-community
      - erroranalysis
      - fairlearn
      - dice-ml
      - econml
      - raiutils
